import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import Theme from './theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  return (
    <html lang={params.locale} dir="rtl">
      <body>
        <AppRouterCacheProvider>
          <Theme>
            <div id="root-layout">{children}</div>
          </Theme>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
