import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import Theme from './theme'
import { NextIntlClientProvider } from 'next-intl'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  let messages
  try {
    messages = (await import(`../../messages/fa.json`)).default
  } catch (error) {
    console.error('Failed to load messages:', error)
  }

  return (
    <html lang={params.locale} dir="rtl">
      <body>
        <AppRouterCacheProvider>
          <NextIntlClientProvider locale={'fa'} messages={messages}>
            <Theme>
              <div id="root-layout">{children}</div>
            </Theme>
          </NextIntlClientProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
